### ISSUE TITLE
Cleanup branches

### ISSUE THREAD

**Issue by dialexo** [clicepfl/clic-website#117]
https://github.com/clicepfl/clic-website/branches is getting bloated with stale branches
We should probably do some housekeeping so that the repo stays clean.

At the time of writing, `quickfix`, `oracleswissquote` and `gonxhe` are merged and without newer commits.
Also branch `MaximeCommissions` is probably supersed by `commissions` (see #114)

Also if possible, we should keep the same branching and naming conventions (namely `{N}-hyphenized-title` where {N} is the issue number attributed by Github), this will make it easier for future maintainers. See https://github.com/clicepfl/clic-website#workflow. It would be great if all content editors could read it.

**Comment by s314cy** [comment]
We went with the `{N}-hyphenized-title` naming convention for future branches. Stale branches were removed.
