### ISSUE TITLE
Optimize images size

### ISSUE THREAD

**Issue by dialexo** [clicepfl/clic-website#121]
A lot of images are unnecessarily large, causing some pages to load very slowly.
See for instance this network capture of the coaching page on a fresh load, no cache:

![image](https://user-images.githubusercontent.com/14943421/110797004-e84d5280-8278-11eb-9428-5804df3b36c6.png)

This degrades the user experience for new visitors, so we should definitely resize all our pictures (also it doesn't make much sense to have images that are sever thousands of pixels in each dimension, especially if the pictures are cropped / resized on the page).

**Comment by s314cy** [comment]
After inspection, this mostly concerns the coaching & news pages. Feel free to spot any other pages with needlessly large images.

**Comment by s314cy** [comment]
Scaled News images to 500px height, scaled Coaching pictures to the same 300-ish px square. Future News images should respect this 500px height

**Comment by s314cy** [comment]
Better go with a 1500px width than 500px height. Don't forget to convert .png portraits to .jpeg. Also, the Commissions pages probably require some image resizing.

**Comment by dialexo** [comment]
Can we close this since #149 is merged? @s314cy
