### ISSUE TITLE
Update ICBD page

### ISSUE THREAD

**Issue by s314cy** [clicepfl/clic-website#126]
Update the ICBD page infos for the upcoming online edition

**Comment by dialexo** [comment]
@s314cy @rayandaod the banner below the logo still mentions "BC BUILDING, EPFL". Consider replacing this text by "online edition" or similar

**Comment by s314cy** [comment]
Two main talks have their spots in the planning interchanged

**Comment by s314cy** [comment]
One of the main talks got cancelled

**Comment by s314cy** [comment]
Nevermind
