### ISSUE TITLE
CLICluedo

### ISSUE THREAD

**Issue by LucasTrg** [clicepfl/clic-website#156]
Hey hey people
As discussed with @Robb-Fr, and I believe that you had a similar suggestion @s314cy, we would need to set the repository to private for the coming weeks in order to allow for the development of CLICluedo to stay hidden.
As such, I would probably need to get contributor's access rights if that doesn't cause any issue.

A proposed workflow could be to branch from main (let's call it CLICluedo) and have an issue per page that needs to be developed. We would then have a separate PR for each of those pages on which we could gradually build upon. 
We can also keep this issue open, using it as a discussion thread for all things related to CLICluedo.

**Comment by dialexo** [comment]
Hey, what about a private fork? Or if not possible, we could simply setup a private copy of the repo as upstream or downstream from this one. Do you want the changes to be permanent?

**Comment by Robb-Fr** [comment]
Hi Alex, 

We discussed about it and considering the emergency, we thought that making the repo private temporarly would be the most convinient for us ^^' 
The changes are not meant to be permanent, we'll insert new pages that contain text, audio and video to guide students through the CLICluedo. Also, some of the existing pages should be altered (on purpose) to hold secrets 👀 

We were looking for the cheapest and easiest method to developp this while keeping an adequate workflow, wdyt ?

**Comment by LucasTrg** [comment]
We were indeed struggling to list out the pros and cons of having a private fork over having the whole repo in private. If we were to fork the repository, how hard would it be to make the switch on the server ? I'm not really knowledgeable about your deployment pipelines

**Comment by dialexo** [comment]
Regarding deployment it wouldn't change much (we would change the remote instead of changing the branch). However I don't know if all the CI pipeline is compatible with a private repo. So it would probably be safer to have a private copy, on which we cant disable it temporarily if needed, rather than changing the infrastructure of this repo.

**Comment by Robb-Fr** [comment]
Ok thanks daddy.
