### ISSUE TITLE
Bug: events summary button broken when less than 3 events displayed on high resolution device

### ISSUE THREAD

**Issue by dialexo** [clicepfl/clic-website#211]
When only 2 events are displayed on the home page, the "Plus d'évènements" button gets broken into several pieces, or moves to the right (because there is enough flex space left by the only 2 events). Depending on the responsive view, the bug showcases a different kind of behaviour:

Examples:

- 1582x1080
  ![image](https://user-images.githubusercontent.com/14943421/139395313-2fa5acf9-9883-48c7-b540-b7d5028f7cfe.png)

- 2290x1080
  ![image](https://user-images.githubusercontent.com/14943421/139395357-a458b147-8891-49f7-837c-f23014f6cdc7.png)

**Comment by Robb-Fr** [comment]
yup I got the same issue
