### ISSUE TITLE
[Sticky] Annual changes to ICBD page

### ISSUE THREAD

**Issue by Robb-Fr** [clicepfl/clic-website#252]
We in general may change slightly the content of the page every year (some talks change, timetable may change, typos ...). Cool to have an issue to reference PRs to about this.

**Comment by s314cy** [comment]
Regarding this issue, we might want to change the current background color to something closer to the orange color? To better fit the new orange logo we have for the upcoming 2022 edition.

**Comment by KevinFaustini** [comment]
Could we :
-  replace "Registrations open soon..." by the registration form link (https://go.epfl.ch/icbd-inscriptions) in the intro 
- replace "Talk" and "Mini-Talks" by "Career Talk" and "Specialization Talks" in the sections title 
- replace "Meetups" by "Meetup Sessions" in the section title 
- move the Data Science talk from BC04 to 02 
- move Networks from BC02 to 04

Thanks my pepireufs
