### ISSUE TITLE
Order ICBD speakers by talk

### ISSUE THREAD

**Issue by s314cy** [clicepfl/clic-website#276]
In order to link speakers to their talks.

**Comment by Robb-Fr** [comment]
I croised Patricia, she told me about a typo: **Martin Galanthay→Márton Galánthay**.
Also, she will send an update of other people that accepted but you can already add Alexandre Margot - Peerdom ( for the talk 10 years after EPFL)
Thanks ma bro

**Comment by s314cy** [comment]
Due to the amount of mini-talks, it is hard to provide the page with a satisfying design. Closing this.
