### ISSUE TITLE
Endpoints or page for commissions

### ISSUE THREAD

**Issue by Battleman** [clicepfl/clic-website#62]
With the official arrival of commissions, CLIC must support and promote them. 
There should be a "generic" way to display them. Either a single page `commissions` with a short description and maybe link to their respective website, or a page _per_ commission, grouped under a single endpoint (e.g. `/commission/ogj`, `/commission/ictravel`,...). 
Left to discuss with the IT team to figure out what is simpler, and what commissions wish to have.

**Comment by dialexo** [comment]
Have each commission write its own Markdown (committed through PR), server can pickup all such files and parse / integrate them automatically into the website (reuse ShowdownJS as in news component)

**Comment by dialexo** [comment]
Probably merged by #114. Should we close?
