### ISSUE TITLE
Link to sponsoring email

### ISSUE THREAD

**Issue by Battleman** [clicepfl/clic-website#72]
Close to the list of sponsors, there should be a message for companies that wish to support us. For example, right below the list of sponsors, a simple text such as 
"Vous souhaitez nous soutenir ? Contactez nous à _sponsoring.clic [at] epfl.ch_"
Not the correctly formatted address (with `@`), to avoid robot spammers.

**Comment by s314cy** [comment]
Should we explicitly give the (clickable) email address in the form of a short text, or rather add a simple button like the "more news" or "statuts de l'association" ones?

**Comment by dialexo** [comment]
A clickable email address would make sense imo
