### ISSUE TITLE
[Discussion] Modify profile contacts of committee members

### ISSUE THREAD

**Issue by Battleman** [clicepfl/clic-website#86]
The current frontpage displays the list of committee members. Currently, when clicking, it redirects to the people.epfl page. It would be worthwile to replace it with the pôle email (it.clic@epfl.ch, administrateur.clic@epfl.ch,...). Visitors are more interested in contacting the pôle rather than the actual person.

This is open to discussion. Any opinion on that?

**Comment by s314cy** [comment]
waiting for the creation of the relations.coaching.clic@epfl.ch (or something similar) email address

**Comment by s314cy** [comment]
reverting to people links
