### ISSUE TITLE
Create static "maintenance" HTML page 

### ISSUE THREAD

**Issue by jonscanzi** [clicepfl/clic-website#9]
This page could then be displayed by the proxy if/when the website server is unavailable.

This is fairly important, as the normal "bad gateway" message from the proxy is fairly ugly.

While this may seem somewhat pointless since both the proxy and the website are running on the same computer, this is for future-proofing if one day the proxy is separate (which is my end-goal)

**Comment by dialexo** [comment]
Maybe we should close this for now @s314cy ? Or we could also implement something similar if we dockerize the website #134, which is displayed automatically whenever the container is down; of course this would not work if the physical server crashes.

**Comment by clicepfl** [comment]
I would go with the 2nd solution and the issue live for now :)
